### PR TITLE
Fix Program::getActiveUniformName()

### PR DESCRIPTION
**Pull request by mrzzzrm**

### CODE REVIEW

**Comment by scheibel** [comment]
The documentation on glGetActiveUniform states:
> glGetActiveUniform returns the name of the uniform variable indicated by index, storing it in the character buffer specified by name. The string returned will be null terminated. The actual number of characters written into this buffer is returned in length, and this count does not include the null termination character. If the length of the returned string is not required, a value of NULL can be passed in the length argument. (https://www.opengl.org/sdk/docs/man/html/glGetActiveUniform.xhtml)

Your implementation assumes the null byte is counted in the length output parameter?

**Comment by scheibel** [comment]
Okay, I just saw we use another method to get the length of the name for active uniforms: https://www.opengl.org/sdk/docs/man/html/glGetActiveUniformsiv.xhtml
> If pname is GL_UNIFORM_NAME_LENGTH, then an array identifying the length, including the terminating null character, of the uniform name strings specified by the corresponding array of uniformIndices is returned. 

Probably we should use the single uniform variant for single uniform requests...

**Comment by mrzzzrm** [comment]
...not sure what you mean by "single uniform variant".
Alas I don't see a way of retrieving the name of uniform with a single gl call, if that's what you're getting at.

**Comment by scheibel** [comment]
One additional method that is used for requesting metadata of a single uniform.
But this has merely to do with this PR, I wanted to document it for later.

**Pull request merged**
